### ISSUE TITLE
Unit test outbound functions

### ISSUE THREAD

**Issue by Daan-Adrichem** [klippa-app/go-pdfium#12]
write tests in file called [file name here]_test.go
these tests should validate that the outbound functionality of pdfium calls the correct internal functions with the correct values.
the internal functions should not be validated however the return values should be logical and true to live (use mocking to replace the internal functions)

**Comment by jerbob92** [comment]
Code is now tested:
 - Directly
 - Through the single_threaded container
 - Through the multi_threaded gRPC container
