### ISSUE TITLE
how to run a demo

### ISSUE THREAD

**Issue by liangzhaoliang95** [klippa-app/go-pdfium#129]
i read you readme and try run it,but it failed
can you supply a whole demo 
thank you

**Comment by liangzhaoliang95** [comment]
![image](https://github.com/klippa-app/go-pdfium/assets/34703350/ea902cb0-0019-4ce9-883f-36fe5578a074)

**Comment by jerbob92** [comment]
I think that happens when it can't find the pdfium headers, is pdfium installs correctly?

**Comment by liangzhaoliang95** [comment]
![image](https://github.com/klippa-app/go-pdfium/assets/34703350/3063f1d9-27fe-46f9-8bff-2bf25d09e90a)
![image](https://github.com/klippa-app/go-pdfium/assets/34703350/0aaa9cf0-7683-4132-92bd-349bd3098f0e)

I followed the readme,my env is wsl

**Comment by jerbob92** [comment]
Is the pkg-config file loaded correctly?

**Comment by liangzhaoliang95** [comment]
can you tell me how to confirm pkg-config load correctly?
thank you .

**Comment by liangzhaoliang95** [comment]
3Q
my wsl env not install pkg-config,when i install it,i success run the demo

**Comment by liangzhaoliang95** [comment]
can you give me a whole example?
how to add text annot to a pdf

func addStickNote(filePath string) (float64, error) {
	// Load the PDF file into a byte array.
	pdfBytes, err := ioutil.ReadFile(filePath)
	if err != nil {
		log.Fatal(err)
	}

	// Open the PDF using PDFium (and claim a worker)
	doc, err := instance.OpenDocument(&requests.OpenDocument{
		File: &pdfBytes,
	})
	if err != nil {
		log.Fatal(err)
	}

	// Always close the document, this will release its resources.
	defer instance.FPDF_CloseDocument(&requests.FPDF_CloseDocument{
		Document: doc.Document,
	})

	// Get the first page of the document.
	page, err := instance.FPDF_LoadPage(&requests.FPDF_LoadPage{
		Document: doc.Document,
		Index:    0,
	})
	if err != nil {
		log.Fatal(err)
	}

	// Always close the page, this will release its resources.
	defer instance.FPDF_ClosePage(&requests.FPDF_ClosePage{
		Page: page.Page,
	})

	// Get the width and height of the page.
	pageWidth, err := instance.FPDF_GetPageWidth(&requests.FPDF_GetPageWidth{
		Page: requests.Page{
			ByIndex:     &requests.PageByIndex{Document: doc.Document, Index: 0},
			ByReference: nil,
		},
	})
	if err != nil {
		log.Fatal(err)
	}

	// 添加注释
	annot, err := instance.FPDFPage_CreateAnnot(&requests.FPDFPage_CreateAnnot{
		Page: requests.Page{
			ByIndex:     &requests.PageByIndex{Document: doc.Document, Index: 0},
			ByReference: nil,
		},
		Subtype: enums.FPDF_ANNOT_SUBTYPE_TEXT,
	})
	log.Printf("%v,%v", annot, err)
	// 设置文字 为我爱你
	_, err = instance.FPDFAnnot_SetStringValue(&requests.FPDFAnnot_SetStringValue{
		Annotation: annot.Annotation,
		Key:        "AAPL:Hash",
		Value:      "Text",
	})
	if err != nil {
		return 0, err
	}
	// 设置注释的位置
	_, err = instance.FPDFAnnot_SetRect(&requests.FPDFAnnot_SetRect{
		Annotation: annot.Annotation,
		Rect:       structs.FPDF_FS_RECTF{Left: 100, Top: 100, Right: 200, Bottom: 200},
	})
	if err != nil {
		return 0, err
	}

	// 写入注释
	_, err = instance.FPDFPage_Flatten(&requests.FPDFPage_Flatten{
		Page: requests.Page{
			ByIndex:     &requests.PageByIndex{Document: doc.Document, Index: 0},
			ByReference: nil,
		},
		Usage: 0,
	})
	if err != nil {
		return 0, err
	}

	// 保存文档
	savePath := "./testdata/output.pdf"
	buffer := bytes.Buffer{}
	rs, err := instance.FPDF_SaveAsCopy(&requests.FPDF_SaveAsCopy{
		Document:   doc.Document,
		FilePath:   &savePath,
		FileWriter: &buffer,
	})
	log.Printf("%v,%v", rs, err)

	return pageWidth.Width, nil
}

this is my try ,but it not work

**Comment by jerbob92** [comment]
@liangzhaoliang95 I can't really help you with how pdfium works, but you probably need to run `FPDFPage_GenerateContent` before you do `FPDFPage_Flatten` and `FPDF_SaveAsCopy`.
