### ISSUE TITLE
Concurrent map read/write in PauseHandles

### ISSUE THREAD

**Issue by mattoberle** [klippa-app/go-pdfium#193]
**Bug Description**

`FPDF_RenderPageBitmap_Start` and `FPDF_RenderPage_Continue` can trigger a panic when utilizing a webassembly pool.
The [PauseHandles](https://github.com/klippa-app/go-pdfium/blob/main/internal/implementation_webassembly/fpdf_progressive.go#L21) map appears to be the culprit.

```
fatal error: concurrent map read and map write

goroutine 155 [running]:
github.com/klippa-app/go-pdfium/internal/implementation_webassembly.(*PdfiumImplementation).FPDF_RenderPage_Continue(0xc000796d80, 0xc000cca000)
        go-pdfium/internal/implementation_webassembly/fpdf_progressive.go:89 +0x14e
github.com/klippa-app/go-pdfium/webassembly.(*pdfiumInstance).FPDF_RenderPage_Continue(0x7fae01e83320?, 0x10?)
        go-pdfium/webassembly/generated.go:5373 +0xbb
```

**Reproduction**

I modified `examples/webassembly/main.go` to create a minimal-ish reproduction of the issue.
Executing `go run .` from `examples/webassembly` triggers the panic.
- https://github.com/mattoberle/go-pdfium/blob/reproduce/examples/webassembly/main.go

The pool sizes and numbers are somewhat arbitrary, the example just sets them high enough to increase the chances of hitting the concurrent access.

**Possible Solutions**

Adding locks surrounding access to the map resolves the issue for me:
- https://github.com/klippa-app/go-pdfium/commit/1a06f0d9741f0a41324888e6c69522d54781c162

There are already instance-level locks on the methods that access the map.
Maybe if the PauseHandles were scoped to the instance the issue could also be avoided?

**Comment by jerbob92** [comment]
This has been released in v1.12.4
