### ISSUE TITLE
Reseach golang packages and setup a clear guide for where which code should live

### ISSUE THREAD

**Issue by Daan-Adrichem** [klippa-app/go-pdfium#4]
Reseach and setup a guide for which code lives where.
Form the current code according to the guide.

Try to add the current code as a package in existing package

**Comment by NL12Daan** [comment]
I think it should probably be something like this

package
  externalfile.go
  internal
    internalfiles.go

**Comment by WimdeJager** [comment]
Useful style guides:
* https://github.com/golang-standards/project-layout/tree/master/pkg
* https://www.reddit.com/r/golang/comments/8g26il/what_is_the_recommended_go_project_folder/
