### ISSUE TITLE
Add Mac OS arm64 build support

### ISSUE THREAD

**Issue by KaymeKaydex** [klippa-app/go-pdfium#65]
always we do cp /opt/pdfium/lib/libpdfium.so /usr/lib/libpdfium.so

but on Mac OS instead of the .so file, libpdfium.dylib is located

**Comment by jerbob92** [comment]
I don't think I need to do anything to make Mac OS work right? The build tests already include Mac OS. On Mac OS you need to set the env variable `env DYLD_LIBRARY_PATH=/opt/pdfium`
Where `/opt/pdfium` is where you extracted a release from https://github.com/bblanchon/pdfium-binaries/releases (either ios-arm64 or ios-x64)

**Comment by jerbob92** [comment]
I'm not completely sure if you actually need it. Might be enough to have the pkg-config. 
Will check soon.

**Comment by gedw99** [comment]
Any chance we can have a simple makefile that does the edge stuff ?

like pull releases from https://github.com/bblanchon/pdfium-binaries/releases 

and build etc

**Comment by KaymeKaydex** [comment]
> Yeah sounds good to me :) I'm not really efficient in Makefiles, but sounds like a good addition to make installs easier, so will accept PR's.
> 
> Actually, won't it be better to add that to `pdfium-binaries`? Then everyone can benefit from it that uses the binaries.

Yes, it would be cool to make a make command that would download the latest version of the compiled library

**Comment by jerbob92** [comment]
I will close this issue for now. I don't think this project should deal with binary distributions of pdfium (except for the Webassembly version). It would be nice if https://github.com/bblanchon/pdfium-binaries could also automatically be pushed to a PPA for Ubuntu/Debian and perhaps to Homebrew for MacOS? I have opened an issue for that on there: https://github.com/bblanchon/pdfium-binaries/issues/114
