### ISSUE TITLE
Library not loaded on macOS

### ISSUE THREAD

**Issue by diegobernardes** [klippa-app/go-pdfium#75]
I'm using a macOS and I'm trying to avoid installing pdfium globally but I'm facing the following problem:
```
dyld[23643]: Library not loaded: ./libpdfium.dylib
  Referenced from: <5A04DF34-A570-3BAD-864E-E1F0BF481CD4> /private/var/folders/c0/klrf3qzn37gd3zfgqsfnfxjc0000gr/T/go-build3974641135/b001/exe/main
  Reason: tried: './libpdfium.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS./libpdfium.dylib' (no such file), './libpdfium.dylib' (no such file), '/usr/local/lib/libpdfium.dylib' (no such file), '/usr/lib/libpdfium.dylib' (no such file, not in dyld cache), '/Users/diego/code/service/cmd/worker/libpdfium.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/diego/code/service/cmd/worker/libpdfium.dylib' (no such file), '/Users/diego/code/service/cmd/worker/libpdfium.dylib' (no such file), '/usr/local/lib/libpdfium.dylib' (no such file), '/usr/lib/libpdfium.dylib' (no such file, not in dyld cache)
signal: abort trap
```

I'm executing the command like this:
```
export DYLD_LIBRARY_PATH=/Users/diego/code/service/misc/pdfium/darwin-arm64/lib
export LD_LIBRARY_PATH=/Users/diego/code/service/misc/pdfium/darwin-arm64/lib
export PKG_CONFIG_PATH=/Users/diego/code/service/misc/pdfium/darwin-arm64
go run main.go
```

I tried `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH`, both failed. If I copy the binary and put at the same folder of the `package main` it works but I'm really trying to avoid that because other developers are using Linux. Any idea on how to fix this problem?

**Comment by diegobernardes** [comment]
Maybe this is because macOS protections? https://hynek.me/articles/macos-dyld-env/

**Comment by jerbob92** [comment]
Hi! Yeah it probably is because of that. We fixed it like [this](https://github.com/klippa-app/go-pdfium/blob/f311054485aa8ccd310061174bd7b7fad381a139/multi_threaded/multi_threaded_test.go#L19) in our tests.
So basically you would have to set the DYLD_LIBRARY_PATH again when running the worker process.

**Comment by diegobernardes** [comment]
I don't understand how the code you posted works because without the library you'll not be able to compile the application.
