### ISSUE TITLE
Retrieving "structured" paths

### ISSUE THREAD

**Issue by cemerick** [klippa-app/go-pdfium#81]
I see that access to "structured" (character-by-character text, with various kinds of style and position metadata) is available via `GetPageTextStructured`.

Is something similar available for retrieving drawn paths (lines and rects, ideally with analogous style metadata like fill and stroke colors)?

Thanks!

**Comment by jerbob92** [comment]
`GetPageTextStructured` is one of the helper methods that this library contains. Currently there is no helper for retrieving paths. I would accept a PR for it though. 

You would probably need:

- `FPDFPage_CountObjects` (to get the amount of objects in a page)
- `FPDFPage_GetObject` (to loop through the objects of a page)
  - `FPDFPageObj_GetType` (to filter those objects to only continue when type is `enums.FPDF_PAGEOBJ_PATH`)
    - `FPDFPageObj_GetBounds` / `FPDFPageObj_GetStrokeColor` / `FPDFPageObj_GetStrokeWidth` / `FPDFPageObj_GetLineJoin` / `FPDFPageObj_GetLineCap` / `FPDFPageObj_GetFillColor` / `FPDFPath_GetDrawMode` (to get the metadata per path)
    - `FPDFPath_CountSegments` (to get the amount of segments in a path)
    - `FPDFPath_GetPathSegment` (to loop through the segments of a path)
      - `FPDFPathSegment_GetPoint` / `FPDFPathSegment_GetType` / `FPDFPathSegment_GetClose` (to get the details of the path segment)
