### ISSUE TITLE
Pdf parser

### ISSUE THREAD

**Issue by gedw99** [klippa-app/go-pdfium#95]
I am using this and figured it might be on interest since it has shared goals.

https://github.com/benoitkugler/pdf

It’s not like other pdf golang packages because it’s a low level pdf parser and builder.

https://github.com/go-text/typesetting Is a 100% golang replacement of harfbuz. It’s heavily used by gio and Fyne, but can be used with he pdf parsing too due to its ability to handle fonts it’s myriad of complexities.

**Comment by jerbob92** [comment]
Thanks! But I don't really think it has shared goals, most of the time pdfium users do not need and/or want low level pdf access.
